# -*- coding: utf-8 -*-
"""LAB01-AIML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kRwq02Py4RsvTEfqPEO6w5Kidc8Wc8ii
"""



"""LIST

List,array,identify the type using type()
"""

import numpy as np
List=[6,17,11,1]
array=np.array(List)
print(array)
type(List)
type(array)

"""Perform Mathematical Operations on these datasets - Multiplication, Division, Poweroff"""

import numpy as np
array1=3
array2=6
print("array2 multiplied by array1: ",array1*array2)
print("array2 divided by array1: ",array2/array1)
print("array2 raised to the power off array1: ",array2**array1)

"""Sine function, Logirthm,Exponential"""

#sine function
import numpy as np
array1=6
print("sine: ",np.sin(array1))
# logarithm
print("Natural logarithm: ",np.log(array1))
print("Base10 logarithm: ",np.log10(array1))
print("Base-2 logarithm: ",np.log2(array1))
#Exponential
print("Exponential:",np.exp(array1))

"""addition of 2 arrays"""

import numpy as np
list1=[3,2,1]
list2=[5,6,7]
array1=np.array(list1)
array2=np.array(list2)
print("Adding two numpy arrays {array1} and {array2} together:",array1+array2)